name: Update Aquila Version

on:
  push:
    branches: [ poc-ssh-remote-commands ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Add new version in package.json
      run: |
        echo "newAquilaVersion=test1" >> $GITHUB_ENV
    - name: Use an ssh script
      uses: appleboy/ssh-action@master
      with:
	host: ${{ secrets.HOSTREC }}
        username: ${{ secrets.USERNAMEREC }}
        password: ${{ secrets.PASSWORDREC }}
        port: ${{ secrets.PORTREC }}
	script: sh /data/scripts/updateAquilaCMS.sh
    - name: Commit file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[github actions] Updating automatically AquilaCMS version number (${newAquilaVersion})"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'poc-ssh-remote-commands'
